// Code generated by "goki generate ./..."; DO NOT EDIT.

package confusion

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:      "github.com/emer/emergent/v2/confusion.Matrix",
	ShortName: "confusion.Matrix",
	IDName:    "matrix",
	Doc:       "Matrix computes the confusion matrix, with rows representing\nthe ground truth correct class, and columns representing the\nactual answer produced.  Correct answers are along the diagonal.",
	Directives: gti.Directives{
		&gti.Directive{Tool: "git", Directive: "add", Args: []string{}},
	},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Prob", &gti.Field{Name: "Prob", Type: "github.com/emer/etable/v2/etensor.Float64", LocalType: "etensor.Float64", Doc: "normalized probability of confusion: Row = ground truth class, Col = actual response for that class.", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"Sum", &gti.Field{Name: "Sum", Type: "github.com/emer/etable/v2/etensor.Float64", LocalType: "etensor.Float64", Doc: "incremental sums", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"N", &gti.Field{Name: "N", Type: "github.com/emer/etable/v2/etensor.Float64", LocalType: "etensor.Float64", Doc: "counts per ground truth (rows)", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"Vis", &gti.Field{Name: "Vis", Type: "github.com/emer/etable/v2/simat.SimMat", LocalType: "simat.SimMat", Doc: "visualization using SimMat", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"TFPN", &gti.Field{Name: "TFPN", Type: "github.com/emer/etable/v2/etensor.Float64", LocalType: "etensor.Float64", Doc: "true pos/neg, false pos/neg for each class, generated from the confusion matrix", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"ClassScores", &gti.Field{Name: "ClassScores", Type: "github.com/emer/etable/v2/etensor.Float64", LocalType: "etensor.Float64", Doc: "precision, recall and F1 score by class", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"MatrixScores", &gti.Field{Name: "MatrixScores", Type: "github.com/emer/etable/v2/etensor.Float64", LocalType: "etensor.Float64", Doc: "micro F1, macro F1 and weighted F1 scores for entire matrix ignoring class", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
