// Code generated by "core generate -add-types"; DO NOT EDIT.

package confusion

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/confusion.Matrix", IDName: "matrix", Doc: "Matrix computes the confusion matrix, with rows representing\nthe ground truth correct class, and columns representing the\nactual answer produced.  Correct answers are along the diagonal.", Directives: []types.Directive{{Tool: "git", Directive: "add"}}, Fields: []types.Field{{Name: "Prob", Doc: "normalized probability of confusion: Row = ground truth class, Col = actual response for that class."}, {Name: "Sum", Doc: "incremental sums"}, {Name: "N", Doc: "counts per ground truth (rows)"}, {Name: "Vis", Doc: "visualization using SimMat"}, {Name: "TFPN", Doc: "true pos/neg, false pos/neg for each class, generated from the confusion matrix"}, {Name: "ClassScores", Doc: "precision, recall and F1 score by class"}, {Name: "MatrixScores", Doc: "micro F1, macro F1 and weighted F1 scores for entire matrix ignoring class"}}})
