// Code generated by "stringer -type=PrjnType"; DO NOT EDIT.

package emer

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _PrjnType_name = "ForwardBackLateralInhibPrjnTypeN"

var _PrjnType_index = [...]uint8{0, 7, 11, 18, 23, 32}

func (i PrjnType) String() string {
	if i < 0 || i >= PrjnType(len(_PrjnType_index)-1) {
		return "PrjnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrjnType_name[_PrjnType_index[i]:_PrjnType_index[i+1]]
}

func (i *PrjnType) FromString(s string) error {
	for j := 0; j < len(_PrjnType_index)-1; j++ {
		if s == _PrjnType_name[_PrjnType_index[j]:_PrjnType_index[j+1]] {
			*i = PrjnType(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: PrjnType")
}
