// Code generated by "goki version"; DO NOT EDIT.

package emer

const (
	// Version is the version of this package being used
	Version = "v2.0.0-dev0.0.5"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "68f9509"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2024-01-12 16:54"
)
