// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package emer

const (
	Version     = "v1.3.2"
	GitCommit   = "7a4cefd"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-03 11:44" // UTC
)
