// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package emer

const (
	Version     = "v1.3.40"
	GitCommit   = "7723e81"          // the commit JUST BEFORE the release
	VersionDate = "2023-02-10 11:35" // UTC
)
