// Code generated by "goki generate ./..."; DO NOT EDIT.

package netparams

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:      "github.com/emer/emergent/v2/netparams.Sets",
	ShortName: "netparams.Sets",
	IDName:    "sets",
	Doc:       "Sets is a collection of Sheets that can be chosen among\ndepending on different desired configurations etc.  Thus, each Set\nrepresents a collection of different possible specific configurations,\nand different such configurations can be chosen by name to apply as desired.",
	Directives: gti.Directives{
		&gti.Directive{Tool: "git", Directive: "add", Args: []string{}},
	},

	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
