// Code generated by "stringer -type=RndDists"; DO NOT EDIT.

package erand

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _RndDists_name = "UniformBinomialPoissonGammaGaussianBetaMeanRndDistsN"

var _RndDists_index = [...]uint8{0, 7, 15, 22, 27, 35, 39, 43, 52}

func (i RndDists) String() string {
	if i < 0 || i >= RndDists(len(_RndDists_index)-1) {
		return "RndDists(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RndDists_name[_RndDists_index[i]:_RndDists_index[i+1]]
}

func (i *RndDists) FromString(s string) error {
	for j := 0; j < len(_RndDists_index)-1; j++ {
		if s == _RndDists_name[_RndDists_index[j]:_RndDists_index[j+1]] {
			*i = RndDists(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: RndDists")
}
