// Code generated by "core generate -add-types"; DO NOT EDIT.

package relpos

import (
	"cogentcore.org/core/gti"
)

var _ = gti.AddType(&gti.Type{Name: "github.com/emer/emergent/v2/relpos.Rel", IDName: "rel", Doc: "Rel defines a position relationship among layers, in terms of X,Y width and height of layer\nand associated position within a given X-Y plane,\nand Z vertical stacking of layers above and below each other.", Directives: []gti.Directive{{Tool: "git", Directive: "add"}}, Fields: []gti.Field{{Name: "Rel", Doc: "spatial relationship between this layer and the other layer"}, {Name: "XAlign", Doc: "] horizontal (x-axis) alignment relative to other"}, {Name: "YAlign", Doc: "] vertical (y-axis) alignment relative to other"}, {Name: "Other", Doc: "name of the other layer we are in relationship to"}, {Name: "Scale", Doc: "scaling factor applied to layer size for displaying"}, {Name: "Space", Doc: "number of unit-spaces between us"}, {Name: "XOffset", Doc: "for vertical (y-axis) alignment, amount we are offset relative to perfect alignment"}, {Name: "YOffset", Doc: "for horizontial (x-axis) alignment, amount we are offset relative to perfect alignment"}}})

var _ = gti.AddType(&gti.Type{Name: "github.com/emer/emergent/v2/relpos.Relations", IDName: "relations", Doc: "Relations are different spatial relationships (of layers)", Directives: []gti.Directive{{Tool: "enums", Directive: "enum"}}})

var _ = gti.AddType(&gti.Type{Name: "github.com/emer/emergent/v2/relpos.XAligns", IDName: "x-aligns", Doc: "XAligns are different horizontal alignments", Directives: []gti.Directive{{Tool: "enums", Directive: "enum"}}})

var _ = gti.AddType(&gti.Type{Name: "github.com/emer/emergent/v2/relpos.YAligns", IDName: "y-aligns", Doc: "YAligns are different vertical alignments", Directives: []gti.Directive{{Tool: "enums", Directive: "enum"}}})
