// Code generated by "stringer -type=Relations"; DO NOT EDIT.

package relpos

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _Relations_name = "NoRelRightOfLeftOfBehindFrontOfAboveBelowRelationsN"

var _Relations_index = [...]uint8{0, 5, 12, 18, 24, 31, 36, 41, 51}

func (i Relations) String() string {
	if i < 0 || i >= Relations(len(_Relations_index)-1) {
		return "Relations(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Relations_name[_Relations_index[i]:_Relations_index[i+1]]
}

func (i *Relations) FromString(s string) error {
	for j := 0; j < len(_Relations_index)-1; j++ {
		if s == _Relations_name[_Relations_index[j]:_Relations_index[j+1]] {
			*i = Relations(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: Relations")
}
