// Code generated by "stringer -type=YAligns"; DO NOT EDIT.

package relpos

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _YAligns_name = "FrontCenterBackYAlignsN"

var _YAligns_index = [...]uint8{0, 5, 11, 15, 23}

func (i YAligns) String() string {
	if i < 0 || i >= YAligns(len(_YAligns_index)-1) {
		return "YAligns(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _YAligns_name[_YAligns_index[i]:_YAligns_index[i+1]]
}

func (i *YAligns) FromString(s string) error {
	for j := 0; j < len(_YAligns_index)-1; j++ {
		if s == _YAligns_name[_YAligns_index[j]:_YAligns_index[j+1]] {
			*i = YAligns(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: YAligns")
}
