// Code generated by "goki generate ./... -add-types"; DO NOT EDIT.

package patgen

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/patgen.Vocab",
	ShortName:  "patgen.Vocab",
	IDName:     "vocab",
	Doc:        "Vocab is a map of named tensors that contain patterns used for creating\nlarger patterns by mixing together.",
	Directives: gti.Directives{},

	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
