// Code generated by "core generate -add-types"; DO NOT EDIT.

package patgen

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/patgen.Vocab", IDName: "vocab", Doc: "Vocab is a map of named tensors that contain patterns used for creating\nlarger patterns by mixing together."})
