// Code generated by "goki generate ./..."; DO NOT EDIT.

package main

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:       "main.Sim",
	ShortName:  "main.Sim",
	IDName:     "sim",
	Doc:        "Sim holds the params, table, etc",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Dist", &gti.Field{Name: "Dist", Type: "github.com/emer/emergent/v2/erand.RndParams", LocalType: "erand.RndParams", Doc: "random params", Directives: gti.Directives{}, Tag: ""}},
		{"NSamp", &gti.Field{Name: "NSamp", Type: "int", LocalType: "int", Doc: "number of samples", Directives: gti.Directives{}, Tag: ""}},
		{"NBins", &gti.Field{Name: "NBins", Type: "int", LocalType: "int", Doc: "number of bins in the histogram", Directives: gti.Directives{}, Tag: ""}},
		{"Range", &gti.Field{Name: "Range", Type: "github.com/emer/etable/v2/minmax.F64", LocalType: "minmax.F64", Doc: "range for histogram", Directives: gti.Directives{}, Tag: ""}},
		{"Table", &gti.Field{Name: "Table", Type: "*github.com/emer/etable/v2/etable.Table", LocalType: "*etable.Table", Doc: "table for raw data", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"Hist", &gti.Field{Name: "Hist", Type: "*github.com/emer/etable/v2/etable.Table", LocalType: "*etable.Table", Doc: "histogram of data", Directives: gti.Directives{}, Tag: "view:\"no-inline\""}},
		{"Plot", &gti.Field{Name: "Plot", Type: "*github.com/emer/etable/v2/eplot.Plot2D", LocalType: "*eplot.Plot2D", Doc: "the plot", Directives: gti.Directives{}, Tag: "view:\"-\""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
