// Code generated by "core generate -add-types"; DO NOT EDIT.

package econfig

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/econfig.TestEnum", IDName: "test-enum", Doc: "TestEnum is an enum type for testing"})

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/econfig.Includeser", IDName: "includeser", Doc: "Includeser enables processing of Includes []string field with files to include in Config objects.", Methods: []types.Method{{Name: "IncludesPtr", Doc: "IncludesPtr returns a pointer to the Includes []string field containing file(s) to include\nbefore processing the current config file.", Returns: []string{"*"}}}})

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/econfig.Includer", IDName: "includer", Doc: "Includer enables processing of Include string field with file to include in Config objects.", Methods: []types.Method{{Name: "IncludePtr", Doc: "IncludePtr returns a pointer to the Include string field containing single file to include\nbefore processing the current config file.", Returns: []string{"*string"}}}})
