// Code generated by "core generate -add-types"; DO NOT EDIT.

package evec

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/evec.Dims", IDName: "dims", Doc: "Dims is a list of vector dimension (component) names"})

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/evec.Vector2i", IDName: "vector2i", Doc: "Vector2i is a 2D vector/point with X and Y int components.", Fields: []types.Field{{Name: "X"}, {Name: "Y"}}})
