// Code generated by "core generate -add-types"; DO NOT EDIT.

package estats

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/emergent/v2/estats.Stats", IDName: "stats", Doc: "Stats provides maps for storing statistics as named scalar and tensor values.\nThese stats are available in the elog.Context for use during logging.", Fields: []types.Field{{Name: "Floats"}, {Name: "Strings"}, {Name: "Ints"}, {Name: "F32Tensors", Doc: "float32 tensors used for grabbing values from layers"}, {Name: "F64Tensors", Doc: "float64 tensors as needed for other computations"}, {Name: "IntTensors", Doc: "int tensors as needed for other computations"}, {Name: "SimMats", Doc: "similarity matrix for comparing pattern similarities"}, {Name: "Plots", Doc: "analysis plots -- created by analysis routines"}, {Name: "Rasters", Doc: "list of layer names configured for recording raster plots"}, {Name: "LinDecoders", Doc: "linear decoders"}, {Name: "SoftMaxDecoders", Doc: "softmax decoders"}, {Name: "Timers", Doc: "named timers available for timing how long different computations take (wall-clock time)"}}})
