// Code generated by "stringer -type=Modes"; DO NOT EDIT.

package etime

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoEvalMode-0]
	_ = x[AllModes-1]
	_ = x[Train-2]
	_ = x[Test-3]
	_ = x[Validate-4]
	_ = x[Analyze-5]
	_ = x[Debug-6]
	_ = x[ModesN-7]
}

const _Modes_name = "NoEvalModeAllModesTrainTestValidateAnalyzeDebugModesN"

var _Modes_index = [...]uint8{0, 10, 18, 23, 27, 35, 42, 47, 53}

func (i Modes) String() string {
	if i < 0 || i >= Modes(len(_Modes_index)-1) {
		return "Modes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modes_name[_Modes_index[i]:_Modes_index[i+1]]
}

func (i *Modes) FromString(s string) error {
	for j := 0; j < len(_Modes_index)-1; j++ {
		if s == _Modes_name[_Modes_index[j]:_Modes_index[j+1]] {
			*i = Modes(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: Modes")
}

var _Modes_descMap = map[Modes]string{
	0: ``,
	1: `AllModes indicates that the log should occur over all modes present in other items.`,
	2: `Train is when the network is learning`,
	3: `Test is when testing, typically without learning`,
	4: `Validate is typically for a special held-out testing set`,
	5: `Analyze is when analyzing the representations and behavior of the network`,
	6: `Debug is for recording info particularly useful for debugging`,
	7: ``,
}

func (i Modes) Desc() string {
	if str, ok := _Modes_descMap[i]; ok {
		return str
	}
	return "Modes(" + strconv.FormatInt(int64(i), 10) + ")"
}
