// Code generated by "goki generate ./... -add-types"; DO NOT EDIT.

package looper

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.Ctr",
	ShortName:  "looper.Ctr",
	IDName:     "ctr",
	Doc:        "Ctr combines an integer with a maximum value. It supports time tracking within looper.",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Cur", &gti.Field{Name: "Cur", Type: "int", LocalType: "int", Doc: "current counter value", Directives: gti.Directives{}, Tag: ""}},
		{"Max", &gti.Field{Name: "Max", Type: "int", LocalType: "int", Doc: "maximum counter value -- only used if > 0", Directives: gti.Directives{}, Tag: ""}},
		{"Inc", &gti.Field{Name: "Inc", Type: "int", LocalType: "int", Doc: "increment per iteration", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.Event",
	ShortName:  "looper.Event",
	IDName:     "event",
	Doc:        "A Event has function(s) that can be called at a particular point\nin the loop, when the counter is AtCtr value.",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Name", &gti.Field{Name: "Name", Type: "string", LocalType: "string", Doc: "Might be 'plus' or 'minus' for example.", Directives: gti.Directives{}, Tag: ""}},
		{"AtCtr", &gti.Field{Name: "AtCtr", Type: "int", LocalType: "int", Doc: "The counter value upon which this Event occurs.", Directives: gti.Directives{}, Tag: ""}},
		{"OnEvent", &gti.Field{Name: "OnEvent", Type: "github.com/emer/emergent/v2/looper.NamedFuncs", LocalType: "NamedFuncs", Doc: "Callback function for the Event.", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.NamedFunc",
	ShortName:  "looper.NamedFunc",
	IDName:     "named-func",
	Doc:        "NamedFunc lets you keep an ordered map of functions.",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Name", &gti.Field{Name: "Name", Type: "string", LocalType: "string", Doc: "", Directives: gti.Directives{}, Tag: ""}},
		{"Func", &gti.Field{Name: "Func", Type: "func()", LocalType: "func()", Doc: "", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.NamedFuncs",
	ShortName:  "looper.NamedFuncs",
	IDName:     "named-funcs",
	Doc:        "NamedFunc is an ordered map of functions.",
	Directives: gti.Directives{},

	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.NamedFuncsBool",
	ShortName:  "looper.NamedFuncsBool",
	IDName:     "named-funcs-bool",
	Doc:        "NamedFuncsBool is like NamedFuncs, but for functions that return a bool.",
	Directives: gti.Directives{},

	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.Loop",
	ShortName:  "looper.Loop",
	IDName:     "loop",
	Doc:        "Loop contains one level of a multi-level iteration scheme.\nIt wraps around an inner loop recorded in a Stack, or around Main functions.\nIt records how many times the loop should be repeated in the Counter.\nIt records what happens at the beginning and end of each loop.\nFor example, a loop with 1 start, 1 end, and a Counter with max=3 will do:\nStart, Inner, End, Start, Inner, End, Start, Inner, End\nWhere the Inner loop is specified by a Stack or by Main,\nand Start and End are functions on the loop.\nSee Stack for more details on how loops are combined.",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Counter", &gti.Field{Name: "Counter", Type: "github.com/emer/emergent/v2/looper.Ctr", LocalType: "Ctr", Doc: "Tracks time within the loop. Also tracks the maximum. OnStart, Main, and OnEnd will be called Ctr.Max times, or until IsDone is satisfied, whichever ends first.", Directives: gti.Directives{}, Tag: ""}},
		{"OnStart", &gti.Field{Name: "OnStart", Type: "github.com/emer/emergent/v2/looper.NamedFuncs", LocalType: "NamedFuncs", Doc: "OnStart is called at the beginning of each loop.", Directives: gti.Directives{}, Tag: ""}},
		{"Main", &gti.Field{Name: "Main", Type: "github.com/emer/emergent/v2/looper.NamedFuncs", LocalType: "NamedFuncs", Doc: "OnStart is called in the middle of each loop. In general, only use Main for the last Loop in a Stack. For example, actual Net updates might occur here.", Directives: gti.Directives{}, Tag: ""}},
		{"OnEnd", &gti.Field{Name: "OnEnd", Type: "github.com/emer/emergent/v2/looper.NamedFuncs", LocalType: "NamedFuncs", Doc: "OnStart is called at the end of each loop.", Directives: gti.Directives{}, Tag: ""}},
		{"IsDone", &gti.Field{Name: "IsDone", Type: "github.com/emer/emergent/v2/looper.NamedFuncsBool", LocalType: "NamedFuncsBool", Doc: "If true, end loop. Maintained as an unordered map because they should not have side effects.", Directives: gti.Directives{}, Tag: ""}},
		{"Events", &gti.Field{Name: "Events", Type: "[]*github.com/emer/emergent/v2/looper.Event", LocalType: "[]*Event", Doc: "Events occur when Ctr.Cur gets to their AtCtr.", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.Manager",
	ShortName:  "looper.Manager",
	IDName:     "manager",
	Doc:        "Manager holds data relating to multiple stacks of loops,\nas well as the logic for stepping through it.\nIt also holds helper methods for constructing the data.\nIt's also a control object for stepping through Stacks of Loops.\nIt holds data about how the flow is going.",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Stacks", &gti.Field{Name: "Stacks", Type: "map[github.com/emer/emergent/v2/etime.Modes]*github.com/emer/emergent/v2/looper.Stack", LocalType: "map[etime.Modes]*Stack", Doc: "map of stacks by Mode", Directives: gti.Directives{}, Tag: ""}},
		{"Mode", &gti.Field{Name: "Mode", Type: "github.com/emer/emergent/v2/etime.Modes", LocalType: "etime.Modes", Doc: "The current evaluation mode.", Directives: gti.Directives{}, Tag: ""}},
		{"isRunning", &gti.Field{Name: "isRunning", Type: "bool", LocalType: "bool", Doc: "Set to true while looping, false when done. Read only.", Directives: gti.Directives{}, Tag: ""}},
		{"lastStartedCtr", &gti.Field{Name: "lastStartedCtr", Type: "map[github.com/emer/emergent/v2/etime.ScopeKey]int", LocalType: "map[etime.ScopeKey]int", Doc: "The Cur value of the Ctr associated with the last started level, for each timescale.", Directives: gti.Directives{}, Tag: ""}},
		{"internalStop", &gti.Field{Name: "internalStop", Type: "bool", LocalType: "bool", Doc: "", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/looper.Stack",
	ShortName:  "looper.Stack",
	IDName:     "stack",
	Doc:        "Stack contains a list of Loops Ordered from top to bottom.\nFor example, a Stack might be created like this:\n\n\tmystack := manager.AddStack(etime.Train).AddTime(etime.Run, 2).AddTime(etime.Trial, 3)\n\tmyStack.Loops[etime.Run].OnStart.Add(\"NewRun\", initRunFunc)\n\tmyStack.Loops[etime.Trial].OnStart.Add(\"PresentTrial\", trialFunc)\n\nWhen run, myStack will behave like this:\ninitRunFunc, trialFunc, trialFunc, trialFunc, initRunFunc, trialFunc, trialFunc, trialFunc",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Mode", &gti.Field{Name: "Mode", Type: "github.com/emer/emergent/v2/etime.Modes", LocalType: "etime.Modes", Doc: "evaluation mode for this stack", Directives: gti.Directives{}, Tag: ""}},
		{"Loops", &gti.Field{Name: "Loops", Type: "map[github.com/emer/emergent/v2/etime.Times]*github.com/emer/emergent/v2/looper.Loop", LocalType: "map[etime.Times]*Loop", Doc: "An ordered map of Loops, from the outer loop at the start to the inner loop at the end.", Directives: gti.Directives{}, Tag: ""}},
		{"Order", &gti.Field{Name: "Order", Type: "[]github.com/emer/emergent/v2/etime.Times", LocalType: "[]etime.Times", Doc: "The list and order of time scales looped over by this stack of loops,  ordered from top to bottom, so longer timescales like Run should be at the beginning and shorter timescales like Trial should be and the end.", Directives: gti.Directives{}, Tag: ""}},
		{"StopNext", &gti.Field{Name: "StopNext", Type: "bool", LocalType: "bool", Doc: "If true, stop model at the end of the current StopLevel.", Directives: gti.Directives{}, Tag: ""}},
		{"StopFlag", &gti.Field{Name: "StopFlag", Type: "bool", LocalType: "bool", Doc: "If true, stop model ASAP.", Directives: gti.Directives{}, Tag: ""}},
		{"StopLevel", &gti.Field{Name: "StopLevel", Type: "github.com/emer/emergent/v2/etime.Times", LocalType: "etime.Times", Doc: "Time level to stop at the end of.", Directives: gti.Directives{}, Tag: ""}},
		{"StopIterations", &gti.Field{Name: "StopIterations", Type: "int", LocalType: "int", Doc: "How many iterations at StopLevel before actually stopping.", Directives: gti.Directives{}, Tag: ""}},
		{"StepLevel", &gti.Field{Name: "StepLevel", Type: "github.com/emer/emergent/v2/etime.Times", LocalType: "etime.Times", Doc: "Saved Time level for stepping -- what was set for last step or by gui.", Directives: gti.Directives{}, Tag: ""}},
		{"StepIterations", &gti.Field{Name: "StepIterations", Type: "int", LocalType: "int", Doc: "Saved number of steps for stepping -- what was set for last step or by gui.", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
