// Code generated by "stringer -type=Elements"; DO NOT EDIT.

package esg

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RuleEl-0]
	_ = x[TokenEl-1]
	_ = x[ElementsN-2]
}

const _Elements_name = "RuleElTokenElElementsN"

var _Elements_index = [...]uint8{0, 6, 13, 22}

func (i Elements) String() string {
	if i < 0 || i >= Elements(len(_Elements_index)-1) {
		return "Elements(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Elements_name[_Elements_index[i]:_Elements_index[i+1]]
}

func (i *Elements) FromString(s string) error {
	for j := 0; j < len(_Elements_index)-1; j++ {
		if s == _Elements_name[_Elements_index[j]:_Elements_index[j+1]] {
			*i = Elements(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: Elements")
}
