// Code generated by "goki generate ./... -add-types"; DO NOT EDIT.

package timer

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:       "github.com/emer/emergent/v2/timer.Time",
	ShortName:  "timer.Time",
	IDName:     "time",
	Doc:        "Time manages the timer accumulated time and count",
	Directives: gti.Directives{},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"St", &gti.Field{Name: "St", Type: "time.Time", LocalType: "time.Time", Doc: "the most recent starting time", Directives: gti.Directives{}, Tag: ""}},
		{"Total", &gti.Field{Name: "Total", Type: "time.Duration", LocalType: "time.Duration", Doc: "the total accumulated time", Directives: gti.Directives{}, Tag: ""}},
		{"N", &gti.Field{Name: "N", Type: "int", LocalType: "int", Doc: "the number of start/stops", Directives: gti.Directives{}, Tag: ""}},
	}),
	Embeds:  ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{}),
})
